CREATE TABLE IF NOT EXISTS SPRING_AI_CHAT_MEMORY (
    conversation_id VARCHAR(36) NOT NULL,
    content CLOB NOT NULL,
    type VARCHAR(10) NOT NULL,
    "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS SPRING_AI_CHAT_MEMORY_CONV_TS_IDX
ON SPRING_AI_CHAT_MEMORY (conversation_id, "timestamp");

ALTER TABLE SPRING_AI_CHAT_MEMORY
ADD CONSTRAINT IF NOT EXISTS SPRING_AI_CHAT_MEMORY_TYPE_CHECK
CHECK (type IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL'));
